version: '2'
services:
    edna-app:
        image: edna
        external_links:
            - edna-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/edna
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    edna-postgresql:
        extends:
            file: postgresql.yml
            service: edna-postgresql
